### PR TITLE
Generate man page with build.rs

### PR DESCRIPTION
**Pull request by luxrck**

### CODE REVIEW

**Comment by luxrck** [comment]
This should fix #35

**Comment by arusahni** [comment]
Thanks for the pr! Regarding the shell completions, could we use the one's Clap can generate? That way git-req can support multiple shells without needing to manually maintain multiple completion files?

**Comment by luxrck** [comment]
The only reason I didn't use it is that I thought generating way is not very good for maintaining especially when we want to implement more complex completion features......

But, yes. We could generate it.

**Comment by arusahni** [comment]
Sorry for the delayed response - this looks solid! Can you rebase so I can accept the request?

**Comment by luxrck** [comment]
I was preparing for the exam last week......
Update the code just now, hope it could meet your request >_<.

**Comment by arusahni** [comment]
No worries! Thanks for your contribution!

**Pull request merged**
